// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/lmcity_1bk.tga
gfx/env/lmcity_1dn.tga
gfx/env/lmcity_1ft.tga
gfx/env/lmcity_1lf.tga
gfx/env/lmcity_1rt.tga
gfx/env/lmcity_1up.tga
models/player/uboa/uboa.bmp
models/player/uboa/uboa.mdl
models/the_daikon_warfare/apache.mdl
models/the_daikon_warfare/bg_massn.mdl
models/the_daikon_warfare/chatarou.mdl
models/the_daikon_warfare/electro_tv.mdl
models/the_daikon_warfare/gamesaba_tv.mdl
models/the_daikon_warfare/mikeneko.mdl
models/the_daikon_warfare/miketama_katana.mdl
models/the_daikon_warfare/miketama_katana_sp.mdl
models/the_daikon_warfare/minigun_loader.mdl
models/the_daikon_warfare/minigun_loadert.mdl
models/the_daikon_warfare/p_2uzis.mdl
models/the_daikon_warfare/p_9mmar.mdl
models/the_daikon_warfare/p_9mmhandgun.mdl
models/the_daikon_warfare/p_crowbar.mdl
models/the_daikon_warfare/p_grenade.mdl
models/the_daikon_warfare/p_medkit.mdl
models/the_daikon_warfare/p_rpg.mdl
models/the_daikon_warfare/p_rpg_r.mdl
models/the_daikon_warfare/p_shotgun.mdl
models/the_daikon_warfare/p_uzi.mdl
models/the_daikon_warfare/rpgrocket.mdl
models/the_daikon_warfare/sat_swat.mdl
models/the_daikon_warfare/shii_statue.mdl
models/the_daikon_warfare/sonchou.mdl
models/the_daikon_warfare/syacho.mdl
models/the_daikon_warfare/syacho_sit.mdl
models/the_daikon_warfare/takuan.mdl
models/the_daikon_warfare/v_9mmar.mdl
models/the_daikon_warfare/v_9mmhandgun.mdl
models/the_daikon_warfare/v_crowbar.mdl
models/the_daikon_warfare/v_grenade.mdl
models/the_daikon_warfare/v_medkit.mdl
models/the_daikon_warfare/v_rpg.mdl
models/the_daikon_warfare/v_shotgun.mdl
models/the_daikon_warfare/v_uzi.mdl
models/the_daikon_warfare/w_2uzis.mdl
models/the_daikon_warfare/w_9mmar.mdl
models/the_daikon_warfare/w_9mmhandgun.mdl
models/the_daikon_warfare/w_crowbar.mdl
models/the_daikon_warfare/w_grenade.mdl
models/the_daikon_warfare/w_pmedkit.mdl
models/the_daikon_warfare/w_rpg.mdl
models/the_daikon_warfare/w_rpgammo.mdl
models/the_daikon_warfare/w_shotgun.mdl
models/the_daikon_warfare/w_uzi.mdl
models/the_daikon_warfare/yakan.mdl
models/the_daikon_warfare/youngppl.mdl
models/uboa/dokupe.mdl
sound/ayakashi/cat.wav
sound/the_daikon_warfare/403_effect.wav
sound/the_daikon_warfare/fnn_news.mp3
sound/the_daikon_warfare/glock_magin.wav
sound/the_daikon_warfare/glock_magout.wav
sound/the_daikon_warfare/glock_slide.wav
sound/the_daikon_warfare/nosound.wav
sound/the_daikon_warfare/nyannyan.wav
sound/the_daikon_warfare/stalker/cop_combat1.mp3
sound/the_daikon_warfare/stalker/cop_combat2.mp3
sound/the_daikon_warfare/stalker/cop_guitar.mp3
sound/the_daikon_warfare/stalker/cs_aes.mp3
sound/the_daikon_warfare/the_rock3.wav
sound/the_daikon_warfare/the_rock4.wav
sound/weapons/ayakashi_weapons/katana_attack1.wav
the_daikon_warfare.wad
