// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/the_daikon_warfare/aan_driver.mdl
models/the_daikon_warfare/apache.mdl
models/the_daikon_warfare/chatarou_run.mdl
models/the_daikon_warfare/driver_bgman.mdl
models/the_daikon_warfare/jetmassn.mdl
models/the_daikon_warfare/jetmassnt.mdl
models/the_daikon_warfare/mikeneko.mdl
models/the_daikon_warfare/miketama_assasin_dual.mdl
models/the_daikon_warfare/p_2uzis.mdl
models/the_daikon_warfare/p_9mmar.mdl
models/the_daikon_warfare/p_9mmhandgun.mdl
models/the_daikon_warfare/p_crowbar.mdl
models/the_daikon_warfare/p_grenade.mdl
models/the_daikon_warfare/p_medkit.mdl
models/the_daikon_warfare/p_rpg.mdl
models/the_daikon_warfare/p_rpg_r.mdl
models/the_daikon_warfare/p_shotgun.mdl
models/the_daikon_warfare/p_uzi.mdl
models/the_daikon_warfare/rpgrocket.mdl
models/the_daikon_warfare/sonchou_driver.mdl
models/the_daikon_warfare/takuan.mdl
models/the_daikon_warfare/v_9mmar.mdl
models/the_daikon_warfare/v_9mmhandgun.mdl
models/the_daikon_warfare/v_crowbar.mdl
models/the_daikon_warfare/v_grenade.mdl
models/the_daikon_warfare/v_medkit.mdl
models/the_daikon_warfare/v_rpg.mdl
models/the_daikon_warfare/v_shotgun.mdl
models/the_daikon_warfare/v_uzi.mdl
models/the_daikon_warfare/w_2uzis.mdl
models/the_daikon_warfare/w_9mmar.mdl
models/the_daikon_warfare/w_9mmhandgun.mdl
models/the_daikon_warfare/w_crowbar.mdl
models/the_daikon_warfare/w_grenade.mdl
models/the_daikon_warfare/w_pmedkit.mdl
models/the_daikon_warfare/w_rpg.mdl
models/the_daikon_warfare/w_rpgammo.mdl
models/the_daikon_warfare/w_shotgun.mdl
models/the_daikon_warfare/w_uzi.mdl
models/the_daikon_warfare/yakan.mdl
models/the_daikon_warfare/youngman_driver.mdl
sound/ayakashi/cat.wav
sound/takedeppo/50cal_fire.wav
sound/the_daikon_warfare/glock_magin.wav
sound/the_daikon_warfare/glock_magout.wav
sound/the_daikon_warfare/glock_slide.wav
sound/the_daikon_warfare/nosound.wav
sound/the_daikon_warfare/nyannyan.wav
sound/the_daikon_warfare/stalker/cs_combat2.mp3
sound/the_daikon_warfare/stalker/cs_combat3.mp3
sound/the_daikon_warfare/the_rock1.wav
sprites/the_daikon_warfare/setbombmsg.spr
the_daikon_warfare.wad
