// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/the_daikon_warfare/chatarou.mdl
models/the_daikon_warfare/driver_bgman.mdl
models/the_daikon_warfare/kokesi.mdl
models/the_daikon_warfare/mikeneko.mdl
models/the_daikon_warfare/miketama_katana.mdl
models/the_daikon_warfare/ojizosama.mdl
models/the_daikon_warfare/p_2uzis.mdl
models/the_daikon_warfare/p_9mmar.mdl
models/the_daikon_warfare/p_9mmhandgun.mdl
models/the_daikon_warfare/p_crowbar.mdl
models/the_daikon_warfare/p_grenade.mdl
models/the_daikon_warfare/p_medkit.mdl
models/the_daikon_warfare/p_rpg.mdl
models/the_daikon_warfare/p_rpg_r.mdl
models/the_daikon_warfare/p_shotgun.mdl
models/the_daikon_warfare/p_uzi.mdl
models/the_daikon_warfare/rpgrocket.mdl
models/the_daikon_warfare/sonchou.mdl
models/the_daikon_warfare/takeobj.mdl
models/the_daikon_warfare/takuan.mdl
models/the_daikon_warfare/v_9mmar.mdl
models/the_daikon_warfare/v_9mmhandgun.mdl
models/the_daikon_warfare/v_crowbar.mdl
models/the_daikon_warfare/v_grenade.mdl
models/the_daikon_warfare/v_medkit.mdl
models/the_daikon_warfare/v_rpg.mdl
models/the_daikon_warfare/v_shotgun.mdl
models/the_daikon_warfare/v_uzi.mdl
models/the_daikon_warfare/w_2uzis.mdl
models/the_daikon_warfare/w_9mmar.mdl
models/the_daikon_warfare/w_9mmhandgun.mdl
models/the_daikon_warfare/w_crowbar.mdl
models/the_daikon_warfare/w_grenade.mdl
models/the_daikon_warfare/w_pmedkit.mdl
models/the_daikon_warfare/w_rpg.mdl
models/the_daikon_warfare/w_rpgammo.mdl
models/the_daikon_warfare/w_shotgun.mdl
models/the_daikon_warfare/w_uzi.mdl
models/the_daikon_warfare/yakan.mdl
models/the_daikon_warfare/youngppl.mdl
sound/ayakashi/cat.wav
sound/takedeppo/50cal_fire.wav
sound/takedeppo/50cal_fun_time.wav
sound/the_daikon_warfare/glock_magin.wav
sound/the_daikon_warfare/glock_magout.wav
sound/the_daikon_warfare/glock_slide.wav
sound/the_daikon_warfare/nosound.wav
sound/the_daikon_warfare/nyannyan.wav
sound/the_daikon_warfare/SC30_Menu-Gleum.wav
sound/the_daikon_warfare/stalker/cs_combat1.mp3
sound/the_daikon_warfare/tam-n09_short.wav
sound/the_daikon_warfare/the_rock1.wav
sound/the_daikon_warfare/the_rock2.wav
sound/weapons/ayakashi_weapons/katana_attack1.wav
the_daikon_warfare.wad
